# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

2.0.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*. (parecido a una matriz*)
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.rand(2, 3, 5)
print(a)

[[[0.70163352 0.77954979 0.44960988 0.88015187 0.94976488]
  [0.35485185 0.60792222 0.36612076 0.45920626 0.5425864 ]
  [0.18632835 0.12934642 0.69145961 0.32795494 0.51944439]]

 [[0.89125408 0.8428105  0.32468677 0.26422415 0.32146972]
  [0.43390472 0.86009634 0.46903714 0.64331979 0.95540613]
  [0.09799231 0.4032409  0.52727411 0.11242894 0.97192062]]]


In [6]:
a = np.random.random((2, 3, 5))
print(a)

[[[0.31592919 0.16928176 0.88514421 0.54711166 0.55601124]
  [0.19538111 0.21745356 0.9271185  0.0164816  0.03554723]
  [0.5782227  0.98125001 0.78130312 0.71016611 0.19977677]]

 [[0.13503181 0.06272017 0.29182281 0.32185369 0.41467649]
  [0.38179514 0.93227647 0.93294137 0.04189906 0.69467602]
  [0.47398704 0.21043973 0.30516845 0.99358292 0.80379931]]]


In [21]:
a = np.random.randint(0, 10, size=(2, 3, 5))
print(a)

[[[3 5 0 6 1]
  [7 3 5 9 1]
  [3 1 8 8 0]]

 [[8 6 7 8 1]
  [1 0 1 8 6]
  [5 1 3 5 6]]]


#### 4. Print *a*.


In [22]:
print(a)

[[[3 5 0 6 1]
  [7 3 5 9 1]
  [3 1 8 8 0]]

 [[8 6 7 8 1]
  [1 0 1 8 6]
  [5 1 3 5 6]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [24]:
b = np.random.randint(1, 2, size=(5, 2, 3))

#### 6. Print *b*.


In [47]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [46]:
#2nd option:
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [26]:
print(a.size)
print(b.size)
#Yes, they have the same size

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [27]:
c = a + b
print(c)
#No, we cannot add a and b because their shapes are different and not the same. Array a has the shape (2, 3, 5) and array b has the shape (5, 2, 3).

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [49]:
c = b.transpose(1, 2, 0)

In [50]:
print(c)
print(c.shape)
print(a)
print(a.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)
[[[3 5 0 6 1]
  [7 3 5 9 1]
  [3 1 8 8 0]]

 [[8 6 7 8 1]
  [1 0 1 8 6]
  [5 1 3 5 6]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [41]:
d = a + c
print(d)
#Yes, it wor because now they have the same shape (2, 3, 5)

[[[ 4.  6.  1.  7.  2.]
  [ 8.  4.  6. 10.  2.]
  [ 4.  2.  9.  9.  1.]]

 [[ 9.  7.  8.  9.  2.]
  [ 2.  1.  2.  9.  7.]
  [ 6.  2.  4.  6.  7.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [42]:
print(a)
print(d)
#The difference is that a contains integer values, while d contains float values (decimals).
#In this operation between an integer array (a) and a float array (c), NumPy automatically converts the result to float.

[[[3 5 0 6 1]
  [7 3 5 9 1]
  [3 1 8 8 0]]

 [[8 6 7 8 1]
  [1 0 1 8 6]
  [5 1 3 5 6]]]
[[[ 4.  6.  1.  7.  2.]
  [ 8.  4.  6. 10.  2.]
  [ 4.  2.  9.  9.  1.]]

 [[ 9.  7.  8.  9.  2.]
  [ 2.  1.  2.  9.  7.]
  [ 6.  2.  4.  6.  7.]]]


In [45]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int64
float64
float64
float64


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [52]:
e = a * c
print(e)

[[[3. 5. 0. 6. 1.]
  [7. 3. 5. 9. 1.]
  [3. 1. 8. 8. 0.]]

 [[8. 6. 7. 8. 1.]
  [1. 0. 1. 8. 6.]
  [5. 1. 3. 5. 6.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [53]:
print(a)
print(e)
#Yes, because the array c has only "1" values.

[[[3 5 0 6 1]
  [7 3 5 9 1]
  [3 1 8 8 0]]

 [[8 6 7 8 1]
  [1 0 1 8 6]
  [5 1 3 5 6]]]
[[[3. 5. 0. 6. 1.]
  [7. 3. 5. 9. 1.]
  [3. 1. 8. 8. 0.]]

 [[8. 6. 7. 8. 1.]
  [1. 0. 1. 8. 6.]
  [5. 1. 3. 5. 6.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [55]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

10.0
1.0
5.2


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [57]:
f = np.empty((2, 3, 5))
print(f)

[[[3. 5. 0. 6. 1.]
  [7. 3. 5. 9. 1.]
  [3. 1. 8. 8. 0.]]

 [[8. 6. 7. 8. 1.]
  [1. 0. 1. 8. 6.]
  [5. 1. 3. 5. 6.]]]


#### 16. Populate the values in *f*.

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [58]:
f[(d == d_min)] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[(d == d_mean)] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_max)] = 100

print(f)

[[[ 25.  75.   0.  75.  25.]
  [ 75.  25.  75. 100.  25.]
  [ 25.  25.  75.  75.   0.]]

 [[ 75.  75.  75.  75.  25.]
  [ 25.   0.  25.  75.  75.]
  [ 75.  25.  25.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [59]:
print(d)
print(f)

[[[ 4.  6.  1.  7.  2.]
  [ 8.  4.  6. 10.  2.]
  [ 4.  2.  9.  9.  1.]]

 [[ 9.  7.  8.  9.  2.]
  [ 2.  1.  2.  9.  7.]
  [ 6.  2.  4.  6.  7.]]]
[[[ 25.  75.   0.  75.  25.]
  [ 75.  25.  75. 100.  25.]
  [ 25.  25.  75.  75.   0.]]

 [[ 75.  75.  75.  75.  25.]
  [ 25.   0.  25.  75.  75.]
  [ 75.  25.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [64]:
f_str = np.empty(f.shape, dtype=str)

f_str[(d == d_min)] = "A"
f_str[(d > d_min) & (d < d_mean)] = "B"
f_str[(d == d_mean)] = "C"
f_str[(d > d_mean) & (d < d_max)] = "D"
f_str[(d == d_max)] = "E"

print(f_str)

[[['B' 'D' 'A' 'D' 'B']
  ['D' 'B' 'D' 'E' 'B']
  ['B' 'B' 'D' 'D' 'A']]

 [['D' 'D' 'D' 'D' 'B']
  ['B' 'A' 'B' 'D' 'D']
  ['D' 'B' 'B' 'D' 'D']]]
